FROM python:3.7-slim

RUN apt-get update

RUN apt-get install -y zip

RUN pip3 install boto3

RUN pip3 install nbformat

RUN pip3 install nbconvert

RUN pip3 install jupyter_client

RUN python --version